import { BlockType } from '../shared/block-types'

// Re-export shared constants for backwards compatibility
export { CHUNK_HEIGHT, CHUNK_SIZE, CHUNK_Y_COUNT, CHUNK_Y_SIZE, TREE_DENSITY, WATER_LEVEL } from '../shared/constants'

// Main thread only constants (not needed by workers)
export const RENDER_DISTANCE = 8
export const RENDER_DISTANCE_Y = 3 // Vertical render distance above player in chunk sections
export const RENDER_DISTANCE_Y_DOWN = 2 // Vertical render distance below player
export const ENABLE_FAR_LOD = false
export const FAR_LOD_DISTANCE = 12
export const LOD_BUDGET_MS = 2
export type LodQuality = 'low' | 'medium' | 'high'
export const DEFAULT_LOD_QUALITY: LodQuality = 'medium'

// Initial loading settings (for fast game start)
export const INITIAL_RENDER_DISTANCE = 2 // Smaller radius for initial load (was 3)
export const INITIAL_RENDER_DISTANCE_Y = 3 // Y axis initial distance (increased from 1 to cover surface chunks)
// Critical chunks - absolute minimum for game to start
export const CRITICAL_RENDER_DISTANCE = 1 // Just immediate surroundings
export const CRITICAL_RENDER_DISTANCE_Y = 3 // Enough to cover ground level (cy=0,1,2,3,4)
export const BLOCK_SIZE = 1
export const GRAVITY = -25
export const JUMP_FORCE = 9
export const PLAYER_HEIGHT = 1.8
export const PLAYER_WIDTH = 0.6
export const MOVE_SPEED = 5
export const MOUSE_SENSITIVITY = 0.002
export const GAMEPAD_LOOK_SENSITIVITY = 0.05 // Gamepad camera rotation sensitivity
export const GAMEPAD_STICK_DEADZONE = 0.15 // Stick deadzone

// Spawn position constants - inland grassland area
export const SPAWN_X = 50
export const SPAWN_Z = 50
export const SPAWN_ROTATION_Y = Math.PI * 0.75 // Face inland (NE direction, away from water)

export const BlockNames: Record<BlockType, string> = {
  [BlockType.AIR]: 'Air',
  [BlockType.GRASS]: 'Grass',
  [BlockType.DIRT]: 'Dirt',
  [BlockType.STONE]: 'Stone',
  [BlockType.SAND]: 'Sand',
  [BlockType.WATER]: 'Water',
  [BlockType.WOOD]: 'Wood',
  [BlockType.LEAVES]: 'Leaves',
  [BlockType.COBBLESTONE]: 'Cobblestone',
  [BlockType.PLANKS]: 'Planks',
  [BlockType.CRAFTING_TABLE]: 'Crafting Table',
  [BlockType.BEDROCK]: 'Bedrock',
  [BlockType.GLASS]: 'Glass',
  [BlockType.BRICK]: 'Brick',
  [BlockType.COAL_ORE]: 'Coal Ore',
  [BlockType.IRON_ORE]: 'Iron Ore',
  [BlockType.GOLD_ORE]: 'Gold Ore',
  [BlockType.DIAMOND_ORE]: 'Diamond Ore',
  [BlockType.SNOW]: 'Snow',
  [BlockType.ICE]: 'Ice',
  [BlockType.BUSH]: 'Bush',
  [BlockType.RED_FLOWER]: 'Red Flower',
  [BlockType.YELLOW_FLOWER]: 'Yellow Flower',
  [BlockType.CACTUS]: 'Cactus',
  [BlockType.PALM_WOOD]: 'Palm Wood',
  [BlockType.PALM_LEAVES]: 'Palm Leaves',
  [BlockType.DEAD_BUSH]: 'Dead Bush',
  [BlockType.BAMBOO]: 'Bamboo',
  [BlockType.SNOW_LEAVES]: 'Snow Leaves',
  [BlockType.SNOW_BUSH]: 'Snow Bush',
  [BlockType.WINTER_FLOWER]: 'Winter Flower',
  [BlockType.FALLEN_LEAVES]: 'Fallen Leaves',
  [BlockType.MOSS]: 'Moss',
  [BlockType.MUSHROOM_RED]: 'Red Mushroom',
  [BlockType.MUSHROOM_BROWN]: 'Brown Mushroom',
  [BlockType.VINE]: 'Vine',
  [BlockType.SNOW_VINE]: 'Snow Vine',
  [BlockType.PACKED_SAND]: 'Packed Sand',
  [BlockType.PEBBLE]: 'Pebble',
  [BlockType.STONE_PEBBLE]: 'Stone Pebble',
  [BlockType.SNOW_PEBBLE]: 'Snow Pebble',
  [BlockType.STARFISH]: 'Starfish',
  [BlockType.APPLE]: 'Apple',
  [BlockType.BASKET]: 'Basket',
  [BlockType.BASKET_APPLES_1]: 'Apple Basket',
  [BlockType.BASKET_APPLES_2]: 'Apple Basket',
  [BlockType.BASKET_APPLES_3]: 'Apple Basket',
  [BlockType.BASKET_APPLES_4]: 'Apple Basket',
  [BlockType.ORANGE]: 'Orange',
  [BlockType.PEACH]: 'Peach',
  [BlockType.BANANA]: 'Banana',
  [BlockType.FARMLAND_DRY]: 'Dry Farmland',
  [BlockType.FARMLAND_WET]: 'Wet Farmland',
  [BlockType.WILD_WHEAT]: 'Wild Wheat',
  [BlockType.WILD_RICE]: 'Wild Rice',
  [BlockType.WHEAT_CROP_1]: 'Wheat Seedling',
  [BlockType.WHEAT_CROP_2]: 'Growing Wheat',
  [BlockType.WHEAT_CROP_3]: 'Heading Wheat',
  [BlockType.RICE_CROP_1]: 'Rice Seedling',
  [BlockType.RICE_CROP_2]: 'Growing Rice',
  [BlockType.RICE_CROP_3]: 'Heading Rice',
  [BlockType.WHEAT_SEEDS]: 'Wheat Seeds',
  [BlockType.RICE_SEEDS]: 'Rice Seeds',
  [BlockType.WHEAT]: 'Wheat',
  [BlockType.RICE]: 'Rice',
  [BlockType.WOODEN_HOE]: 'Wooden Hoe',
  [BlockType.BREAD]: 'Bread',
  [BlockType.RICE_BOWL]: 'Rice Bowl',
  [BlockType.WHEAT_CROP_4]: 'Mature Wheat',
  [BlockType.RICE_CROP_4]: 'Mature Rice',
  [BlockType.WOODEN_BUCKET]: 'Wooden Bucket',
  [BlockType.WATER_BUCKET]: 'Water Bucket',
  [BlockType.FLOUR]: 'Flour',
  [BlockType.DOUGH]: 'Dough',
}

export const BlockHardness: Record<BlockType, number> = {
  [BlockType.AIR]: 0,
  [BlockType.GRASS]: 0.6,
  [BlockType.DIRT]: 0.5,
  [BlockType.STONE]: 1.5,
  [BlockType.SAND]: 0.5,
  [BlockType.WATER]: -1,
  [BlockType.WOOD]: 2.0,
  [BlockType.LEAVES]: 0.2,
  [BlockType.COBBLESTONE]: 2.0,
  [BlockType.PLANKS]: 1.5,
  [BlockType.CRAFTING_TABLE]: 1.5,
  [BlockType.BEDROCK]: -1,
  [BlockType.GLASS]: 0.3,
  [BlockType.BRICK]: 2.0,
  [BlockType.COAL_ORE]: 3.0,
  [BlockType.IRON_ORE]: 3.0,
  [BlockType.GOLD_ORE]: 3.0,
  [BlockType.DIAMOND_ORE]: 3.0,
  [BlockType.SNOW]: 0.2,
  [BlockType.ICE]: 0.5,
  [BlockType.BUSH]: 0.1,
  [BlockType.RED_FLOWER]: 0.1,
  [BlockType.YELLOW_FLOWER]: 0.1,
  [BlockType.CACTUS]: 0.4,
  [BlockType.PALM_WOOD]: 2.0,
  [BlockType.PALM_LEAVES]: 0.2,
  [BlockType.DEAD_BUSH]: 0.1,
  [BlockType.BAMBOO]: 0.3,
  [BlockType.SNOW_LEAVES]: 0.2,
  [BlockType.SNOW_BUSH]: 0.1,
  [BlockType.WINTER_FLOWER]: 0.1,
  [BlockType.FALLEN_LEAVES]: 0.1,
  [BlockType.MOSS]: 0.1,
  [BlockType.MUSHROOM_RED]: 0.1,
  [BlockType.MUSHROOM_BROWN]: 0.1,
  [BlockType.VINE]: 0.1,
  [BlockType.SNOW_VINE]: 0.1,
  [BlockType.PACKED_SAND]: 0.8,
  [BlockType.PEBBLE]: 0.2,
  [BlockType.STONE_PEBBLE]: 0.3,
  [BlockType.SNOW_PEBBLE]: 0.2,
  [BlockType.STARFISH]: 0.1,
  [BlockType.APPLE]: 0.1,
  [BlockType.BASKET]: 0.5,
  [BlockType.BASKET_APPLES_1]: 0.5,
  [BlockType.BASKET_APPLES_2]: 0.5,
  [BlockType.BASKET_APPLES_3]: 0.5,
  [BlockType.BASKET_APPLES_4]: 0.5,
  [BlockType.ORANGE]: 0.1,
  [BlockType.PEACH]: 0.1,
  [BlockType.BANANA]: 0.1,
  [BlockType.FARMLAND_DRY]: 0.5,
  [BlockType.FARMLAND_WET]: 0.5,
  [BlockType.WILD_WHEAT]: 0.1,
  [BlockType.WILD_RICE]: 0.1,
  [BlockType.WHEAT_CROP_1]: 0.1,
  [BlockType.WHEAT_CROP_2]: 0.1,
  [BlockType.WHEAT_CROP_3]: 0.1,
  [BlockType.WHEAT_CROP_4]: 0.1,
  [BlockType.RICE_CROP_1]: 0.1,
  [BlockType.RICE_CROP_2]: 0.1,
  [BlockType.RICE_CROP_3]: 0.1,
  [BlockType.RICE_CROP_4]: 0.1,
  [BlockType.WHEAT_SEEDS]: 0.1,
  [BlockType.RICE_SEEDS]: 0.1,
  [BlockType.WHEAT]: 0.1,
  [BlockType.RICE]: 0.1,
  [BlockType.WOODEN_HOE]: 0.5,
  [BlockType.BREAD]: 0.1,
  [BlockType.RICE_BOWL]: 0.1,
  [BlockType.WOODEN_BUCKET]: 0.4,
  [BlockType.WATER_BUCKET]: 0.4,
  [BlockType.FLOUR]: 0.1,
  [BlockType.DOUGH]: 0.1,
}

export const BlockColors: Record<BlockType, { all?: number; top?: number; bottom?: number; side?: number }> = {
  [BlockType.AIR]: { all: 0x000000 },
  [BlockType.GRASS]: {
    top: 0x5d9b37,
    bottom: 0x8b6914,
    side: 0x8b6914,
  },
  [BlockType.DIRT]: { all: 0x8b6914 },
  [BlockType.STONE]: { all: 0x7f7f7f },
  [BlockType.SAND]: { all: 0xe3d59e },
  [BlockType.WATER]: { all: 0x3366aa },
  [BlockType.WOOD]: {
    top: 0x6b5030,
    bottom: 0x6b5030,
    side: 0x8b6842,
  },
  [BlockType.LEAVES]: { all: 0x2d8a2d },
  [BlockType.COBBLESTONE]: { all: 0x6a6a6a },
  [BlockType.PLANKS]: { all: 0xbc9862 },
  [BlockType.CRAFTING_TABLE]: {
    top: 0x825d32,
    bottom: 0xbc9862,
    side: 0xbc9862,
  },
  [BlockType.BEDROCK]: { all: 0x2a2a2a },
  [BlockType.GLASS]: { all: 0xc8dcff },
  [BlockType.BRICK]: { all: 0x8b4533 },
  [BlockType.COAL_ORE]: { all: 0x6a6a6a },
  [BlockType.IRON_ORE]: { all: 0x8a7a6a },
  [BlockType.GOLD_ORE]: { all: 0x8a7a5a },
  [BlockType.DIAMOND_ORE]: { all: 0x6a8a8a },
  [BlockType.SNOW]: { all: 0xf0f0f0 },
  [BlockType.ICE]: { all: 0xa0c0e0 },
  [BlockType.BUSH]: { all: 0x50e878 },
  [BlockType.RED_FLOWER]: { all: 0xff0000 },
  [BlockType.YELLOW_FLOWER]: { all: 0xffff00 },
  [BlockType.CACTUS]: { all: 0x558822 },
  [BlockType.PALM_WOOD]: { all: 0x8b6914 },
  [BlockType.PALM_LEAVES]: { all: 0x7a9a45 },
  [BlockType.DEAD_BUSH]: { all: 0x8b5a2b },
  [BlockType.BAMBOO]: { all: 0x7cb342 },
  [BlockType.SNOW_LEAVES]: { all: 0xf0f8ff },
  [BlockType.SNOW_BUSH]: { all: 0xe8f4fc },
  [BlockType.WINTER_FLOWER]: { all: 0xeef5ff },
  [BlockType.FALLEN_LEAVES]: { all: 0xa0522d },
  [BlockType.MOSS]: { all: 0x3d6a37 },
  [BlockType.MUSHROOM_RED]: { all: 0xcc2222 },
  [BlockType.MUSHROOM_BROWN]: { all: 0x8b6914 },
  [BlockType.VINE]: { all: 0x2d7a2d },
  [BlockType.SNOW_VINE]: { all: 0xe8f4fc },
  [BlockType.PACKED_SAND]: { all: 0xc9b080 },
  [BlockType.PEBBLE]: { all: 0x8a8a8a },
  [BlockType.STONE_PEBBLE]: { all: 0x6a6a6a },
  [BlockType.SNOW_PEBBLE]: { all: 0xf0f0f0 },
  [BlockType.STARFISH]: { all: 0xff6b4a },
  [BlockType.APPLE]: { all: 0xff2d35 },
  [BlockType.BASKET]: { all: 0x9a6a34 },
  [BlockType.BASKET_APPLES_1]: { all: 0x9a6a34 },
  [BlockType.BASKET_APPLES_2]: { all: 0x9a6a34 },
  [BlockType.BASKET_APPLES_3]: { all: 0x9a6a34 },
  [BlockType.BASKET_APPLES_4]: { all: 0x9a6a34 },
  [BlockType.ORANGE]: { all: 0xff8a12 },
  [BlockType.PEACH]: { all: 0xffb184 },
  [BlockType.BANANA]: { all: 0xffd84a },
  [BlockType.FARMLAND_DRY]: { all: 0x7b4f27 },
  [BlockType.FARMLAND_WET]: { all: 0x8a6242 },
  [BlockType.WILD_WHEAT]: { all: 0xd7b24a },
  [BlockType.WILD_RICE]: { all: 0x9fd96b },
  [BlockType.WHEAT_CROP_1]: { all: 0x8cc95f },
  [BlockType.WHEAT_CROP_2]: { all: 0xb7c752 },
  [BlockType.WHEAT_CROP_3]: { all: 0xe0b84c },
  [BlockType.WHEAT_CROP_4]: { all: 0xe8c761 },
  [BlockType.RICE_CROP_1]: { all: 0x73c95d },
  [BlockType.RICE_CROP_2]: { all: 0x90d66d },
  [BlockType.RICE_CROP_3]: { all: 0xd9eaa0 },
  [BlockType.RICE_CROP_4]: { all: 0xe4efae },
  [BlockType.WHEAT_SEEDS]: { all: 0xb8873a },
  [BlockType.RICE_SEEDS]: { all: 0xdfe9b0 },
  [BlockType.WHEAT]: { all: 0xd7a944 },
  [BlockType.RICE]: { all: 0xf0edd1 },
  [BlockType.WOODEN_HOE]: { all: 0xa87945 },
  [BlockType.BREAD]: { all: 0xc9823b },
  [BlockType.RICE_BOWL]: { all: 0xf0f0e0 },
  [BlockType.WOODEN_BUCKET]: { all: 0x8b5a2b },
  [BlockType.WATER_BUCKET]: { all: 0x3d76b8 },
  [BlockType.FLOUR]: { all: 0xf1e4c8 },
  [BlockType.DOUGH]: { all: 0xd8b67f },
}
