import type { DebugStats } from '../game/engine'

export const DEFAULT_DEBUG_STATS: DebugStats = {
  loadedChunks: 0,
  activeChunks: 0,
  culledChunks: 0,
  cachedChunks: 0,
  cachedMeshes: 0,
  queueLength: 0,
  meshQueueSize: 0,
  lodEnabled: false,
  lodActiveSections: 0,
  lodQueueSize: 0,
  lodProcessingCount: 0,
  lodDroppedTasks: 0,
  lodUpdateMs: 0,
  visibleMeshes: 0,
  totalFaces: 0,
  isLoading: false,
  playerChunkX: 0,
  playerChunkZ: 0,
  frameTime: 0,
  drawCalls: 0,
  triangles: 0,
  workerCount: 0,
  busyWorkers: 0,
  pendingTasks: 0,
  chunkMemory: 0,
  meshMemory: 0,
  totalMemory: 0,
}
